### ISSUE TITLE
Should support java 1.7

### ISSUE THREAD

**Issue by ahonor** [latamdevs/rundeck-puppetenterprise-nodes-plugin#1]
Currently requires 1.8

**Comment by miguelantonio** [comment]
It runs on 1.7 as well, but if you want we can make the code 1.7 (and goodbye lambdas :)

cc @robertopaez

**Comment by ahonor** [comment]
Ok, I got this error when trying the build: 

    Caused by: java.lang.UnsupportedClassVersionError: com/rundeck/plugin/resources/puppetdb/ResourceModelFactory : Unsupported major.minor version 52.0

**Comment by miguelantonio** [comment]
Oh! what's your java -version?

**Comment by ahonor** [comment]
java -version
java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)

**Comment by miguelantonio** [comment]
back to the 1.7 then ;)

**Comment by ahonor** [comment]
Maybe keep 1.8 source but change build to create a 1.7 compatible binary.

**Comment by miguelantonio** [comment]
@ahonor just released 0.2 full compatible with 1.7

https://github.com/latamdevs/rundeck-puppetenterprise-nodes-plugin/releases/tag/v0.2-alpha
