### ISSUE TITLE
Feature: PuppetDB Query as a parameter

### ISSUE THREAD

**Issue by dustinak** [latamdevs/rundeck-puppetenterprise-nodes-plugin#3]
Hiya, so I was wondering if there had been any thought in allowing us to specify a query parameter in the config here. For instance, in my environment, I'm only importing nodes from PuppetDB if they contain a specific puppet class (that lays down the ssh key for the rundeck user remotely).

Thanks!

**Comment by miguelantonio** [comment]
Hi, yes, filters are currently in discussion (bring all then filter), good idea using queries
