### ISSUE TITLE
Identify the expected files in ssl dir for the documetnation

### ISSUE THREAD

**Issue by ahonor** [latamdevs/rundeck-puppetenterprise-nodes-plugin#5]
The ssl directory assumes three files named a specify way (see [PEM_SSLSocketFactoryProvider](https://github.com/latamdevs/rundeck-puppetenterprise-nodes-plugin/blob/master/src/main/java/com/puppetlabs/puppetdb/javaclient/impl/PEM_SSLSocketFactoryProvider.java))

* {ssldir}/ca/ca_crt.pem
* {ssldir}/certs/localhost.pem
* {ssldir}/private_keys/localhost.pem

This should be noted in the README.md

Alternatively, this could be managed as three different plugin config properties so users aren't required to follow this directory/file naming convention.

**Comment by miguelantonio** [comment]
@ahonor this is a mistake, the usual puppet convention is <HOST>.pem in each dir, not localhost, I'll make the change and add documentation
