### ISSUE TITLE
Can't start puppet-enterprise plugin, Missing properties: 'PROPERTY_PUPPETDB_HOST,PROPERTY_PUPPETDB_PORT'

### ISSUE THREAD

**Issue by mtward** [latamdevs/rundeck-puppetenterprise-nodes-plugin#8]
Can you assist?

2016-01-28 10:57:55,540 [qtp1892971028-59] ERROR com.dtolabs.rundeck.core.common.ProjectNodeSupport - Failed loading resource model source #1, skipping: com.dtolabs.rundeck.core.plugins.configuration.ConfigurationException: Can't start puppet-enterprise plugin, Missing properties: 'PROPERTY_PUPPETDB_HOST,PROPERTY_PUPPETDB_PORT'
com.dtolabs.rundeck.core.resources.ResourceModelSourceServiceException: com.dtolabs.rundeck.core.plugins.configuration.ConfigurationException: Can't start puppet-enterprise plugin, Missing properties: 'PROPERTY_PUPPETDB_HOST,PROPERTY_PUPPETDB_PORT'

Here is my project configuration file:

#Thu Jan 28 11:19:08 EST 2016
#edit below
project.description=test
project.name=test
project.ssh-authentication=password
project.ssh-keypath=/var/lib/rundeck/.ssh/id_rsa
resources.source.1.config.host=puppetmaster
resources.source.1.config.port=80
resources.source.1.config.useDefaultMapping=true
resources.source.1.type=puppet-enterprise
service.FileCopier.default.provider=jsch-scp
service.NodeExecutor.default.provider=jsch-ssh

**Comment by mtward** [comment]
curl works fine:

$curl http://puppetmaster/pdb/query/v4/nodes | head
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0[ {
  "catalog-environment" : "live",
  "catalog-timestamp" : "2016-01-28T14:08:20.638Z",
  "certname" : "ejapp2t.renamed.to.protect.the.innocent",
  "deactivated" : null,
  "facts-environment" : "live",
  "facts-timestamp" : "2016-01-28T14:08:15.264Z",
  "report-environment" : "live",
  "report-timestamp" : "2016-01-28T14:08:36.116Z"

**Comment by mtward** [comment]
Ah, it looks like the README is incorrect?

These settings got me up and running.  Thanks for creating this great tool!

resources.source.1.config.PROPERTY_METRICS_INTERVAL=15
resources.source.1.config.PROPERTY_PUPPETDB_HOST=puppetmaster
resources.source.1.config.PROPERTY_PUPPETDB_PORT=80
resources.source.1.type=puppet-enterprise

**Comment by ahonor** [comment]
@mtward did you get it working with those property names? (e.g., `.PROPERTY_PUPPETDB_PORT`)

**Comment by miguelantonio** [comment]
@mtward it seems the README lacks the guidelines to configure directly from property file, it only describes the GUI version of the property names, please confirm it did work and I'll update the documentation

Thanks :) !

**Comment by mtward** [comment]
Yes, these settings worked:

resources.source.1.config.PROPERTY_METRICS_INTERVAL=15
resources.source.1.config.PROPERTY_PUPPETDB_HOST=puppetmaster
resources.source.1.config.PROPERTY_PUPPETDB_PORT=80
resources.source.1.type=puppet-enterprise

I tried first in Rundeck to 'Edit Configuration File'.  When I tried again with 'Simple Configuration' and edited the resource model source, I was prompted for the host, port, etc.

**Comment by miguelantonio** [comment]
Thanks!! we just uploaded a better explanation based on your feedback!
